# Generated by Django 4.0.6 on 2022-08-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=35)),
                ('Telefono', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=40)),
                ('Dia_Check_In', models.DateField()),
                ('Dia_Check_Out', models.DateField()),
                ('Adultos', models.IntegerField(default=0)),
                ('Niños', models.IntegerField(default=0)),
                ('Nota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('reseña', models.TextField()),
            ],
        ),
    ]
