# Generated by Django 4.0.6 on 2022-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagen_casa',
            field=models.ImageField(null=True, upload_to='imagenes_casas'),
        ),
    ]
