# Generated by Django 4.0.6 on 2022-09-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_casa_imagen_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=35)),
                ('Titulo', models.CharField(max_length=35)),
                ('Cuerpo', models.TextField(max_length=4000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen_blog')),
            ],
        ),
    ]
